<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Throttle</RootNamespace>
    <AssemblyName>Throttle</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.17.0" />
    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.12.2" />
  </ItemGroup>
</Project>
